AWSTemplateFormatVersion: '2010-09-09'
Description: A AWS VPC with 3 subnets.
Parameters:
  vpcName:
    Type: String
    Default: MyNewVPC
    Description: Name of VPC
  vpcCidr:
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
    - 10.0.0.0/16
    - 192.168.0.0/16
    - 172.31.0.0/16
    Description: Cidr for the VPC from the user
  subnetACidr:
    Type: String
    Description: Cidr for the SubnetA from the user
  subnetBCidr:
    Type: String
    Description: Cidr for the SubnetB from the user
  subnetCCidr:
    Type: String
    Description: Cidr for the SubnetC from the user
  AMI:
    Description: "AMI for Instance"
    Type: String
  KeyName:
    Description: "Key Name for Instance"
    Type: String    
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: vpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value:
          Ref: vpcName
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs:
            Ref: AWS::Region
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: subnetACidr
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: subnet1
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs:
            Ref: AWS::Region
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: subnetBCidr
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: subnet2
  SubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 2
        - Fn::GetAZs:
            Ref: AWS::Region
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: subnetCCidr
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: subnet3
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: myRouteTable
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTable
  SubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: SubnetA
  SubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: SubnetB
  SubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: SubnetC
  application:
   Type: 'AWS::EC2::SecurityGroup'
   Properties:
      GroupDescription: Base Security Group
      SecurityGroupIngress:
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 22
           ToPort: 22
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 80
           ToPort: 80
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 443
           ToPort: 443
         - IpProtocol: tcp
           CidrIp: 0.0.0.0/0
           FromPort: 8000
           ToPort: 8000
      VpcId: !Ref VPC 
  Ec2Instance: 
   Type: AWS::EC2::Instance
   Properties: 
    ImageId:
      Ref: AMI
    KeyName:
      Ref: KeyName
    InstanceType: "t2.micro"
    BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "false"
          VolumeSize: "20"
    NetworkInterfaces:
      - AssociatePublicIpAddress: "true"
        DeleteOnTermination: "true"
        SubnetId: 
          Ref: SubnetA
        DeviceIndex: "0"
        GroupSet:
          Fn::Split:
            - ","
            - !Ref application        
